version: 2.1
workflows:
  build:
    jobs:
      - build:
          context:
            - circleci-api
            - ngviz

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:current
    resource_class: large
    environment:
      node_version: 18.16.0
    steps:
      - checkout
       # look for existing cache and restore if found
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            # CircleCI will use the static fallback key v1-deps- to load the most recent valid cache
            - v1-deps- 
      # install dependencies 
      - run:
          name: Install dependencies
          command: |
            nvm install $node_version
            nvm use $node_version
            npm install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules   
      - run:
          name: Run tests
          command: |
            npm run test:
      - store_artifacts:
          path: theSrc/test/snapshots
